import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const posts = api.example.obtenerPosts.useQuery();

  const daError = api.example.daError.useQuery();

  const algoDeAndy = api.blog.andy.useQuery({
    name: "andy",
    edad: 15,
  });

  return (
    <>
      <Head>
        <title>Maquinas maquiavelicas del mal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {"Benvenuti "}
            <span className="text-[hsl(280,100%,70%)]">
              Maquinas maquiavelicas
            </span>{" "}
            del mal
          </h1>

          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>

          {daError.isLoading && <div>Loading error...</div>}

          {daError.isError && (
            <div>
              <div className="text-2xl text-white">
                ERROR {"->:"} {daError.error.data?.code}
              </div>
              <div className="text-2xl text-white">{daError.error.message}</div>
            </div>
          )}

          {algoDeAndy.data && (
            <div className="text-2xl text-white">{algoDeAndy.data.message}</div>
          )}

          {/* {posts.data?.map((post) => (
            <div key={post.id}>
              <p>{post.title}</p>
              <p>{post.content}</p>
            </div>
          ))} */}
        </div>
      </main>
    </>
  );
};

export default Home;
